/* tests/test_parity_torch.cpp - Plan 13 stub.
 *
 * Verifies the torch parity baseline bundle structurally. The actual C++
 * vs torch tensor comparison loop is added in Plans 8-12 as each numerical
 * module is rewritten against real upstream rfdetr.
 *
 * The bundle is generated by: `make rfdetr_baseline_torch`
 * (requires .venv/ with rfdetr 1.7.0, torch 2.5.1, gguf, numpy installed).
 *
 * If the bundle hasn't been generated yet, this test SKIPS gracefully (exit 0).
 * Plans 8-12 will tighten this into a per-module comparison.
 */
#include "test_assert.hpp"
#include "ggml.h"
#include "gguf.h"

#include <sys/stat.h>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

namespace {

bool file_exists(const std::string& p) {
    struct stat st;
    return ::stat(p.c_str(), &st) == 0;
}

} // namespace

int main() {
    const std::string fixtures = RFDETR_TEST_FIXTURES;
    const std::string path = fixtures + "/baseline_torch.gguf";

    if (!file_exists(path)) {
        std::fprintf(stderr,
            "[test_parity_torch] SKIPPED: baseline not generated. "
            "Run 'make rfdetr_baseline_torch' (or `cmake --build build "
            "--target rfdetr_baseline_torch`) to produce it.\n");
        return 0;
    }

    ggml_context* ctx = nullptr;
    gguf_init_params init_p{};
    init_p.no_alloc = false;
    init_p.ctx      = &ctx;
    gguf_context* g = gguf_init_from_file(path.c_str(), init_p);
    RFDETR_ASSERT(g != nullptr);
    RFDETR_ASSERT(ctx != nullptr);

    /* Metadata: format version + reference tag */
    {
        int64_t kid = gguf_find_key(g, "parity.format.version");
        RFDETR_ASSERT(kid >= 0);
        RFDETR_ASSERT_STR_EQ(gguf_get_val_str(g, kid), "2");
    }
    {
        int64_t kid = gguf_find_key(g, "parity.reference");
        RFDETR_ASSERT(kid >= 0);
        RFDETR_ASSERT_STR_EQ(gguf_get_val_str(g, kid), "torch");
    }
    {
        int64_t kid = gguf_find_key(g, "parity.input_shape");
        RFDETR_ASSERT(kid >= 0);
    }

    const int64_t nt = gguf_get_n_tensors(g);
    std::fprintf(stderr, "[test_parity_torch] bundle has %lld tensors\n",
                 (long long)nt);

    /* Required checkpoint names. Plan 13 captures ~32; we list the ones that
     * matter for Plans 8-12 to anchor their per-module comparisons. */
    const char* required[] = {
        "parity.preprocess.input",
        "parity.backbone.patch_embed.output",
        "parity.backbone.block.0.output",
        "parity.backbone.block.11.output",
        "parity.backbone.norm.output",
        "parity.backbone.multiscale.level0",
        "parity.backbone.multiscale.level3",
        "parity.projector.output",
        "parity.projector.cv1.output",
        "parity.projector.cv2.output",
        "parity.projector.final_norm.output",
        "parity.two_stage.enc_output_norm.output",
        "parity.two_stage.enc_out_class.output",
        "parity.decoder.layer.0.output",
        "parity.decoder.layer.2.output",
        "parity.decoder.norm.output",
        "parity.heads.class_logits",
        "parity.heads.bbox_pred",
    };
    const size_t n_required = sizeof(required) / sizeof(required[0]);

    int missing = 0;
    for (size_t i = 0; i < n_required; ++i) {
        const char* name = required[i];
        ggml_tensor* t = ggml_get_tensor(ctx, name);
        if (!t) {
            std::fprintf(stderr,
                "[test_parity_torch] MISSING required tensor: %s\n", name);
            ++missing;
            continue;
        }
        std::fprintf(stderr,
            "[test_parity_torch] OK %s ne=[%lld,%lld,%lld,%lld]\n",
            name,
            (long long)t->ne[0], (long long)t->ne[1],
            (long long)t->ne[2], (long long)t->ne[3]);
    }
    RFDETR_ASSERT_EQ_INT(missing, 0);

    gguf_free(g);
    ggml_free(ctx);

    std::fprintf(stderr,
        "[test_parity_torch] PASS: %zu required checkpoints present "
        "(bundle has %lld total)\n",
        n_required, (long long)nt);
    return 0;
}
